project: 
  type: website
  output-dir: output
website:
  repo-url: https://github.com/sdgis-edu-tud/report-asa2025-groupf
  repo-actions: [edit, source, issue]
format:
  html:
    embed-resources: true
    toc: true